<a href="https://colab.research.google.com/github/Eunwoo-1213/BIGDATA_ANALYZE/blob/main/06W_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

### 다양한 데이터 프레임

In [ ]:
# 방법1
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name="courses")
fees = pd.Series([250000, 300000, 200000], name="fees")
df1 = pd.DataFrame([courses, fees])
df1

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

In [ ]:
print(df1.T)

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
# 방법2
df2 = pd.DataFrame()

df2[courses.name] = courses
df2[fees.name] = fees
df2

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
#여러 dict의 목록 데이터 사용
import pandas as pd

df1 = pd.DataFrame([
    {'국어': 70, '수학': 89, '영어': 90},
    {'국어': 80, '영어': 99},
    {'수학': 66, '영어': 78}
])
df1

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [ ]:
s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])

df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3})
df

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [ ]:
df.index = ['노', '장', '박', '강']
df

   국어  영어  수학
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [ ]:
#데이터프레임의 결측값 표시 NaN
import pandas as pd

df1 = pd.DataFrame({
    'A': pd.Series([10, 20, 30], index=[0, 1, 2]),
    'B': pd.Series([3, 2, 1], index=[1, 2, 3])
})
df1

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [ ]:
s1 = pd.Series([90, 80, 60], index=['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

df2 = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3},
                   index=['노', '장', '박', '강'])
df2

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [ ]:
#df.dtypes
import pandas as pd
import numpy as np

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df
df.dtypes

col1    int64
col2    int64
dtype: object

In [ ]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

###날짜 date_range()

In [ ]:
import pandas as pd

dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [ ]:
dates = pd.date_range("20250101", end="20250110")
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates = pd.date_range("20250101", periods=6, freq='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [ ]:
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_1105/3819429892.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [ ]:
dates = pd.date_range("20250101", periods=6, freq='W')
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
import pandas as pd

dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [ ]:
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [ ]:
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_1105/746379463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [ ]:
#날짜 DataFrame
import pandas as pd
import numpy as np

dates = pd.date_range("20250302", periods=6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-03-02 -0.544944  0.386527 -1.054094 -1.718183
2025-03-03  0.037099  0.853869 -0.294677 -0.216326
2025-03-04  0.169357 -0.393827 -1.684704 -0.268081
2025-03-05 -1.036965  0.762005  0.930480  1.281550
2025-03-06 -0.847465  0.616547  0.869942 -0.781793
2025-03-07 -0.723603 -0.130663 -0.398795  0.246538

In [ ]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})

df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

### DataFrame 다양한 참조

In [ ]:
pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# 열 참조
print(pf['중간'])
print()

print(pf.중간)
print()

print(pf['출석'])
print()

print(pf[['출석']])
print()

print(pf[['기말', '출석', '중간']])
print()

print(pf[['기말']])

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [ ]:
#행 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
print(pf['중간'] > 20)
print()

print(pf[pf['중간'] > 20])
print()

print(pf[pf['출석'] >= 19])
print()

print(pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)])

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# loc
print(pf.loc['윤일형'])
print()

print(pf.loc[['윤일형']])
print()

print(pf.loc[['홍소희', '윤일형']])
print()

print(pf.loc['윤일형':'유한빈'])
print()

print(pf.loc[pf.중간 > 20])
print()

print(pf.loc[(pf.중간 > 10) & (pf.과제 == 10)])

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

     중간  기말  과제  출석
윤일형  25  35   8  18

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
#index 행 참조
print(pf.loc[pf.index[0]])
print()

print(pf.loc[[pf.index[0]]])
print()

print(pf.loc[pf.index[1:4]])
print()

print(pf.loc[pf.index[1:4]][['기말', '과제']])

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

     중간  기말  과제  출석
윤일형  25  35   8  18

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
#loc 열 참조
print(pf.loc[:, '과제'])
print()

print(pf.loc[:, '중간':'과제'])
print()

print(pf.loc[:, ['기말', '출석']])

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
#loc columns 열 참조
print(pf.loc[:, pf.columns[0]])
print()

print(pf.loc[:, [pf.columns[0]]])
print()

print(pf.loc[:, pf.columns[1:]])
print()

print(pf.loc[:, pf.columns[1:]][['기말', '과제']])

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
#행과 열 참조
print(pf.loc['윤일형', '출석'])
print()

print(pf.loc['윤일형':'유한빈', '기말'])
print()

print(pf.loc['윤일형':'유한빈', '기말':'과제'])   #앞 뒤 둘다 : 이면 DataFrame으로 결과 나
print()

print(pf.loc[pf.index[0], pf.columns[1]])
print()

print(pf.loc[pf.index[0:3], pf.columns[2]])
print()

print(pf.loc[pf.index[0:3], pf.columns[2:]])

18

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

35

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# df.iloc
print(pf.iloc[1])
print()

print(pf.iloc[[1]])
print()

print(pf.iloc[[1, 3]])
print()

print(pf.iloc[2:])

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

     중간  기말  과제  출석
강수희  18  27  10  20

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# df.iloc[:, 정수]
print(pf.iloc[:, 2])
print()

print(pf.iloc[:, [2]]) # 앞 뒤 둘중에 리스트로 한 번더 덮으면 Df
print()

print(pf.iloc[:, 1:])

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# df.iloc[행번호, 열번호]
print(pf.iloc[1, 1])
print()

print(pf.iloc[1:3, 1:])
print()

print(pf.iloc[:, 1:])
print()

print(pf.iloc[[1, 3, 4], 1:])
print()

print(pf.iloc[[1, 3, 4], [0, 1]])

27

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# at['행명', '열명'] 참조 쓰는 이유는 이렇게 사용하면 빠름
print(pf.at['윤일형', '과제'])
print()

print(pf.at['유한빈', '기말'])
print()

print(pf.at[pf.index[1], '출석'])
print()

print(pf.at[pf.index[3], pf.columns[2]])

8

22

20

9

In [ ]:
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
# iat
print(pf.iat[1, 2])
print()

print(pf.iat[2, 3])

10

19

### 실습

In [ ]:
df = pd.read_csv("2016년졸음운전.csv",
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [ ]:
print(df)
print()

print(df.sum(axis=0)) # 사고열 사망열 부상열
print()

print(df.sum(axis=1)) # 사고행 사망행 부상행

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64